version: '3'

services:

  elasticsearch:
    container_name: learn-elasticsearch
    image: elasticsearch:7.16.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  redis:
    container_name: learn-redis
    image: redis
    ports:
      - 6379:6379